# Ignore false positive from Rails' ActionText and ActiveStorage
ActionText::RichText:
  enabled: false
ActiveStorage::Attachment:
  enabled: false
ActiveStorage::Blob:
  enabled: false
ActiveStorage::VariantRecord:
  enabled: false

DatabaseConsistencySettings:
  color: true


AdminUser:
  email:
    ColumnPresenceChecker:
      enabled: false
  password:
    ColumnPresenceChecker:
      enabled: false

Log::EmailLog:
  contact:
    ForeignKeyChecker:
      enabled: false
  smtp_connection:
    ForeignKeyChecker:
      enabled: false

System::ApiAccess:
  id:
    PrimaryKeyTypeChecker:
      enabled: false

Routing::NumberlistAction:
  numberlist_actions_name_key:
    UniqueIndexChecker:
      enabled: false

Routing::CustomerAuthSrcNameField:
  customers_auth_src_name_fields_name_key:
    UniqueIndexChecker:
      enabled: false


Routing::NumberlistMode:
  blacklist_modes_name_key:
    UniqueIndexChecker:
      enabled: false

Routing::CustomerAuthSrcNumberField:
  customers_auth_src_number_fields_name_key:
    UniqueIndexChecker:
      enabled: false

Routing::RoutingTagMode:
  routing_tag_modes_name_key:
    UniqueIndexChecker:
      enabled: false

Routing::DestinationRatePolicy:
  destination_rate_policy_name_key:
    UniqueIndexChecker:
      enabled: false

Routing::CustomerAuthDstNumberField:
  customers_auth_dst_number_fields_name_key:
    UniqueIndexChecker:
      enabled: false

ActiveRecord::SchemaMigration:
  unique_public.schema_migrations:
    UniqueIndexChecker:
      enabled: false

DiversionPolicy:
  diversion_policy_name_key:
    UniqueIndexChecker:
      enabled: false

Codec:
  codecs_name_key:
    UniqueIndexChecker:
      enabled: false

DisconnectCodeNamespace:
  disconnect_code_namespace_name_key:
    UniqueIndexChecker:
      enabled: false

DumpLevel:
  dump_level_name_key:
    UniqueIndexChecker:
      enabled: false

SdpCLocation:
  sdp_c_location_name_key:
    UniqueIndexChecker:
      enabled: false

Lnp::DatabaseSipRedirectFormat:
  lnp_databases_30x_redirect_formats_name_key:
    UniqueIndexChecker:
      enabled: false

Billing::InvoicePeriod:
  invoice_periods_name_key:
    UniqueIndexChecker:
      enabled: false

System::DtmfSendMode:
  dtmf_send_modes_name_key:
    UniqueIndexChecker:
      enabled: false

System::DtmfReceiveMode:
  dtmf_receive_modes_name_key:
    UniqueIndexChecker:
      enabled: false

System::SipSchema:
  sip_schemas_name_key:
    UniqueIndexChecker:
      enabled: false

System::SensorLevel:
  sensor_levels_name_key: 
    UniqueIndexChecker:
      enabled: false

Equipment::GatewayMediaEncryptionMode:
  gateway_media_encryption_modes_name_key:
    UniqueIndexChecker:
      enabled: false

Equipment::GatewayNetworkProtocolPriority:
  gateway_network_protocol_priorities_name_key:
    UniqueIndexChecker:
      enabled: false

Equipment::TransportProtocol:
  transport_protocols_name_key:
    UniqueIndexChecker:
      enabled: false

Equipment::GatewayGroupBalancingMode:
  gateway_group_balancing_modes_name_key:
    UniqueIndexChecker:
      enabled: false

Equipment::GatewayInbandDtmfFilteringMode:
  gateway_inband_dtmf_filtering_modes_name_key: 
    UniqueIndexChecker:
      enabled: false

Equipment::GatewayRel100Mode:
  gateway_rel100_modes_name_key:
    UniqueIndexChecker:
      enabled: false




Cdr::Cdr:
  time_start:
    NullConstraintChecker:
      enabled: false

  rateplan:
    ForeignKeyChecker:
      enabled: false
  routing_group:
    ForeignKeyChecker:
      enabled: false
  src_area:
    ForeignKeyChecker:
      enabled: false
  dst_area:
    ForeignKeyChecker:
      enabled: false
  routing_plan:
    ForeignKeyChecker:
      enabled: false
  orig_gw:
    ForeignKeyChecker:
      enabled: false
  term_gw:
    ForeignKeyChecker:
      enabled: false
  destination:
    ForeignKeyChecker:
      enabled: false
  destination_rate_policy:
    ForeignKeyChecker:
      enabled: false
  dialpeer:
    ForeignKeyChecker:
      enabled: false
  customer_auth:
    ForeignKeyChecker:
      enabled: false
  vendor_acc:
    ForeignKeyChecker:
      enabled: false
  customer_acc:
    ForeignKeyChecker:
      enabled: false
  vendor:
    ForeignKeyChecker:
      enabled: false
  customer:
    ForeignKeyChecker:
      enabled: false
  disconnect_initiator:
    ForeignKeyChecker:
      enabled: false
  vendor_invoice:
    ForeignKeyChecker:
      enabled: false
  customer_invoice:
    ForeignKeyChecker:
      enabled: false
  node:
    ForeignKeyChecker:
      enabled: false
  pop:
    ForeignKeyChecker:
      enabled: false
  dump_level:
    ForeignKeyChecker:
      enabled: false
  src_network:
    ForeignKeyChecker:
      enabled: false
  src_country:
    ForeignKeyChecker:
      enabled: false
  dst_network:
    ForeignKeyChecker:
      enabled: false
  dst_country:
    ForeignKeyChecker:
      enabled: false
  lnp_database:
    ForeignKeyChecker:
      enabled: false
  auth_orig_transport_protocol:
    ForeignKeyChecker:
      enabled: false
  sign_orig_transport_protocol:
    ForeignKeyChecker:
      enabled: false
  sign_term_transport_protocol:
    ForeignKeyChecker:
      enabled: false

Cdr::RtpStatistic:
  time_start:
    NullConstraintChecker:
      enabled: false
  gateway:
    ForeignKeyChecker:
      enabled: false
  pop:
    ForeignKeyChecker:
      enabled: false
  node:
    ForeignKeyChecker:
      enabled: false

Cdr::AuthLog:
  request_time:
    NullConstraintChecker:
      enabled: false

Cdr::Country:
  id:
    NullConstraintChecker:
      enabled: false

Cdr::Network:
  id:
    NullConstraintChecker:
      enabled: false

Cdr::NetworkPrefix:
  id:
    NullConstraintChecker:
      enabled: false

