name: Build docker images
on:
  workflow_dispatch:
  schedule:
    - cron: '6 9 * * SUN'

jobs:
  deb11-build-image:
    name: Build deb11 images for CI
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Bullseye build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ci/bullseye-build.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/yeti-web/build-image:bullseye

  deb12-build-image:
    name: Build deb12 images for CI
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Bookworm build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ci/bookworm-build.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/yeti-web/build-image:bookworm

  postgres-13-build-image:
    name: Build Postgresql 13 images for CI
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push db image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ci/pg13.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/yeti-web/pgsql:13

  postgres-15-build-image:
    name: Build Postgresql 15 images for CI
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push db image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ci/pg15.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/yeti-web/pgsql:15
