name: Nigthly packages build

on:
  push:
    branches: [ master ]

jobs:
  deb12:
    name: Debian 12 nightly package building
    runs-on: ubuntu-latest
    container: ghcr.io/yeti-switch/yeti-web/build-image:bookworm
    services:
      db:
        image: ghcr.io/yeti-switch/yeti-web/pgsql:16

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: set git safe directory
        run: git config --global --add safe.directory '*'
          
      - name: Build package
        run: make package
        env:
          YETI_DB_HOST: db
          YETI_DB_PORT: 5432
          CDR_DB_HOST: db
          CDR_DB_PORT: 5432
          PACKAGE_TYPE: nightly

      - name: Save deb package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: deb12-package
          path: /__w/yeti-web/*.deb

      - name: Upload package to ${{github.ref}} repo
        env:
          PKG_API_BASE: ${{secrets.PKG_API_BASE}}
        run: ci/deploy.sh bookworm nightly main ../*.deb

  deb12_container:
    name: Debian 12 container
    needs: deb12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: deb12-package

      - name: Display structure of downloaded files
        run: ls -la

      - name: Display path
        run: pwd

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ci/nightly-package.Dockerfile
          push: true
          tags: ghcr.io/yeti-switch/yeti-web:nightly-build

