name: Nigthly packages build

on:
  push:
    branches: [ master ]

jobs:
  deb10:
    name: Debian 10 nightly package building
    runs-on: ubuntu-latest
    container: switchyeti/yeti-web:buster-build
    needs: rspec
    steps:
      - uses: actions/checkout@v2
      - name: Build package
        run: make package
      - name: Upload package to ${{github.ref}} repo
        run: ci/deploy.sh "$API_ENDPOINT" buster nightly main /build/*.deb

