name: Tests

on:
  push:
    branches: [ master, github_actions ]
  pull_request:
    branches: [ master, github_actions ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: switchyeti/yeti-web:buster-build
    services:
      db:
        image: switchyeti/yeti-web:pg13

    steps:
      - uses: actions/checkout@v2
      - name: install gems
        run: make gems-test
      - name: Run rspec
        run: make rspec
        env:
          YETI_DB_HOST: db
          YETI_DB_PORT: 5432
          CDR_DB_HOST: db
          CDR_DB_PORT: 5432


