name: Tests

on:
  push:
    branches: [ master, github_actions ]
  pull_request:
    branches: [ master, github_actions ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: switchyeti/yeti-web:buster-build
    steps:
      - uses: actions/checkout@v2
      - name: install gems
        run: make gems-test
      - name: Rubocop and bundle audit
        run: make lint

  pgq-processors:
    runs-on: ubuntu-latest
    container: switchyeti/yeti-web:buster-build
    services:
      db:
        image: switchyeti/yeti-web:pg13

    steps:
      - uses: actions/checkout@v2
      - name: install gems
        run: make gems-test
      - name: Run test-pgq-processors
        run: make test-pgq-processors
        env:
          YETI_DB_HOST: db
          YETI_DB_PORT: 5432
          CDR_DB_HOST: db
          CDR_DB_PORT: 5432

  test:
    runs-on: ubuntu-latest
    container: switchyeti/yeti-web:buster-build
    services:
      db:
        image: switchyeti/yeti-web:pg13

    strategy:
      fail-fast: false
      matrix:
        # Set N number of parallel jobs you want to run tests on.
        # Use higher number if you have slow tests to split them on more parallel jobs.
        # Remember to update ci_node_index below to 0..N-1
        ci_node_total: [3]
        # set N-1 indexes for parallel jobs
        # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
        ci_node_index: [0, 1, 3]

    steps:
      - uses: actions/checkout@v2
      - name: install gems
        run: make gems-test
      - name: Run rspec
        run: make rspec
        env:
          PARALLEL_TEST_PROCESSORS: ${{ matrix.ci_node_total }}
          TEST_GROUP: ${{ matrix.ci_node_index }}
          YETI_DB_HOST: db
          YETI_DB_PORT: 5432
          CDR_DB_HOST: db
          CDR_DB_PORT: 5432

