name: Tests

on:
  push:
    branches: [ master, github_actions ]
  pull_request:
    branches: [ master, github_actions ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: yeti-web:build-buster
    services:
      db:
        image: switchyeti/yeti-web:pg13

    steps:
      - uses: actions/checkout@v2
      - name: test
        run: make rspec
